### ISSUE TITLE
notes and highlights

### ISSUE THREAD

**Issue by cptchi** [obscuredetour/goodreads-dark#1]
this is a suggestion for something to be done in the next fix it possible - if you visit a person's profile who has kindle notes & highlights, you'll see that the text is a pastel yellow background and light grey letters, making the highlights impossible to read. 

![goodreads](https://i.imgur.com/uFvKvqn.png)

thx for the style btw - goodreads has been needing a (working) darker style for a long time!

**Comment by obscuredetour** [comment]
Hey @cptchi, glad you enjoy the style!

:+1: Thanks for bringing this to my attention. [Goodreads](https://www.goodreads.com) is so huge that there are many aspects of the site I do not use and/or see.

This should be fixed in the latest version 0865cad799d6861ffbd21879ec251eb9e1b95dd2.
