### ISSUE TITLE
Shelf settings

### ISSUE THREAD

**Issue by cptchi** [obscuredetour/goodreads-dark#3]
Hi Jeffrey!
Sorry to bother again and thanks for fixing the highlights last time
I found another part of the website which the theme doesn't affect yet - Shelf settings and batch edit
![batch](https://i.imgur.com/Vxc0Cdw.png)
![settings](https://i.imgur.com/oXSHClT.png)

**Comment by obscuredetour** [comment]
Hey @cptchi,

It's not a bother! Thanks for bringing it to my attention. It should be fixed in v1.7.6, the latest commit 6887dbdb128ee745c4171642b2ab3e4a35d1ee5b.

Cheers!
